### ISSUE TITLE
cannot download default.json - ERROR 404: Not Found

### ISSUE THREAD

**Issue by gerda39** [ZacBlanco/hwx-tutorials#69]
Hey, Zac. I am a total newbie at this, and there might be a better place to leave this comment - my apologies for that. I am stepping through Hortonworks' Analyzing Twitter Data With Apache NiFi and HDP Search tutorial from here http://hortonworks.com/hadoop-tutorial/how-to-refine-and-visualize-sentiment-data/. When I execute line <wget https://raw.githubusercontent.com/ZacBlanco/hwx-tutorials/master/assets/nifi-sentiment-analytics/assets/default.json> I get:

--2016-01-31 05:01:28-- https://raw.githubusercontent.com/ZacBlanco/hwx-tutorials/master/assets/nifi-sentiment-analytics/assets/default.json
Resolving raw.githubusercontent.com... 23.235.44.133
Connecting to raw.githubusercontent.com|23.235.44.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-01-31 05:01:28 ERROR 404: Not Found.

I tried this from two different VMs, one of them being Hortonworks' Sandbox, with the same result. It is very likely that I am doing something wrong, but on an off chance that something in the file's location has changed, I thought I check with you. Many thanks in advance if you get a chance to take a look at this, and if you don't, obviously, I understand that you have better things to do than answer every dilettante's question... ;)

Thanks,

G

**Comment by ZacBlanco** [comment]
Hey there! I just saw your issue. I've gone ahead and updated the that part of the tutorial with a new link.

Sorry about that! Changes should be reflected on the site as well.

Let me know if you have any other problems, or drop us a line at [http://community.hortonworks.com](http://community.hortonworks.com)!

-Zac

**Comment by ZacBlanco** [comment]
Closing issue per commit  d79411a @gerda39
